/** @file */
#include <iostream>
#include <exception>

#include "utils.hpp"


// Forward declare tests
int @FUNC_NAME@();


// Main function
int main() {
	try {
		return @FUNC_NAME@();
	}
	catch(const Utils::Error::Claricpp & e) {
		std::cout << e.what() << std::endl;
		return -1;
	}
	catch(const std::exception & e) {
		std::cout << "Non-claricppy exception: " << e.what() << std::endl;
		return -1;
	}
}
